(******************************************************
  WARNING: This file was generated by kc v1.05
  CopyWrong 1994 by Kenneth Geisshirt.
  Fri Sep 15 00:00:15 1995
*******************************************************)
CONST
n=6;
np=6;
VAR
HBrO2:LONGREAL;
P:LONGREAL;
Br_m:LONGREAL;
CeIV:LONGREAL;
HBrO:LONGREAL;
BrO2:LONGREAL;
BrMA:LONGREAL;
BrO3_m:LONGREAL;
H_p:LONGREAL;
H2O:LONGREAL;
CeIII:LONGREAL;
MA:LONGREAL;
j0:LONGREAL;
kf6:LONGREAL;
species : ARRAY[1..n] OF STRING[20];
